### PR TITLE
Fix for Reindexing issue and back-office UI to re-index

### PR DESCRIPTION
**Pull request by protherj**
Added null check during reindexing to prevent failure if location props were null.  

Added a way to reindex from the back-office via the "Actions" menu in the Locations in the uLocate custom section.

### CODE REVIEW

**Comment by hfloyd** [comment]
Hi Jason! Thanks for the fix. I hadn't experienced that issue before...
Just this past week I made some fixes - where the index wasn't updating when creating/deleting new locations in the back-office. Also I changed the name of the "TestApi" to "PublicApi", so reindexing could be scheduled as well via the umbracosettings.config. Not sure  if that would change your updates at all?

**Comment by hfloyd** [comment]
Ah, I see you are using a different controller entirely. So I don't think that will cause an issue. :-)

**Comment by protherj** [comment]
Cool, thanks for merging it in!  I'll keep pushing back updates if I fix anything else.

**Comment by hfloyd** [comment]
Sure! I hope you got the recent updates for the create/delete issue...

**Comment by protherj** [comment]
I updated to the latest before changing anything, just in case you had already addressed it.  Glad to see its still being maintained!

**Pull request merged**
